### ISSUE TITLE
Support for DFTB+ and CP2k

### ISSUE THREAD

**Issue by tanoury1** [team-mayes/atesa#2]
Hi,
I sat through a recorded lecture from Prof. Baron Peters on TPS and aimless shooting.  I am excited to see how it works for my systems, but LAMMPS is not going to work for me.  Have you thought of providing support for DFTB+, and maybe even CP2K.  My ultimate interest would be in using AIMD/QMC for more accurate calculations, but I do not know what that would cost in computer resources.  Would AIMD be cost prohibitive in this case?

Best regards,
Jerry

**Comment by tuckerburgin** [comment]
Hi Jerry,

Thanks for your interest! While I could certainly develop support for DFTB+ or CP2K, is there something about Amber's QM/MM module that does not suit your needs? It does have support for DFT and AIMD. Check out page 165 of the Amber20 documentation, for example: https://ambermd.org/doc12/Amber20.pdf

As for whether AIMD would be cost-prohibitive, it really depends on your system. I would suggest benchmarking the performance of your model first. Depending on the steepness of the free energy profile that describes the rare event you're interested in, it will usually take on the order of hundreds of femtoseconds per aimless shooting simulation, and you should expect to need on the order of thousands (or sometimes tens of thousands) of simulations in total. You can estimate the computational expense of aimless shooting from there, though keep in mind that you'll also need to budget for umbrella sampling separately if you want to obtain a free energy profile.

I expect you could cut down on the expense dramatically if you're willing to settle for a cheaper QM method like DFTB, but of course whether or not that's appropriate will depend on your system.

**Comment by tanoury1** [comment]
Thank you!  I haven't worked with Amber before, but with DFTB and DFT support and several other features, this could  work for me.  I assume, therefore, that atesa has full support for Amber.

**Comment by tuckerburgin** [comment]
Yes, in fact Amber is the only MD program that ATESA currently supports.

Give it a shot! For now I'll close this issue, but let me know if you need any help getting things set up.

**Comment by tuckerburgin** [comment]
Revisiting this briefly to note that I have now implemented support for CP2K. It will hit the main branch soon, but in the mean time the (potentially still a bit buggy) code can be found on the CP2K branch.

@tanoury1 I'm not sure if you ever got the chance to try out ATESA with Amber, but either way, perhaps this will be of interest to you!

**Comment by tanoury1** [comment]
Thank you for letting me know.  I have been keeping an eye on the code
development and was waiting for your CP2K implementation. Great News!!
I've still got "learning Amber' on my to-do list, but it may be some time
until I actually get that done.

Jerry
