### ISSUE TITLE
Error when trying find_ts in examples directory

### ISSUE THREAD

**Issue by tanoury1** [team-mayes/atesa#4]
Hi,
I created a conda environment for atesa using python 3.7.  After activating the env, I installed atesa with 'pip install atesa'.  I went to the find_ts directory in examples, edited the config file to update paths to input_files and template_files.  I then ran 'atesa ts_find.config', but got the error attached.

It seems to be a syntax error.

Thank you for the help,
Jerry
[find_ts_error-out.txt](https://github.com/team-mayes/atesa/files/14012439/find_ts_error-out.txt)

**Comment by tuckerburgin** [comment]
Hello, so sorry for the long delay in getting back to you. I lost access to the email address associated with this account and was not receiving notifications!

Maybe you have already moved on, but in case this is still useful to you, the error you're facing has to do with a mismatch between the version of python you're using and the version of Django you have installed. Probably pip should have notified you of this error, but maybe the Django repo is not set up to check for a compatible python version. The `:=` operator used in that bit of Django code was added to Python in version 3.8.
